In [1]:
import numpy as np
np.random.seed(1221)

In [2]:
import pandas as pd
df1=pd.read_csv('Attack.csv')
df2=pd.read_csv('environmentMonitoring.csv')
df3=pd.read_csv('patientMonitoring.csv')
df = pd.concat(
    map(pd.read_csv, ['Attack.csv', 'environmentMonitoring.csv','patientMonitoring.csv']), ignore_index=True)
df.head()

C:\Users\siddh\AppData\Local\Temp\ipykernel_19236\137588759.py:2: DtypeWarning: Columns (26,28,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df1=pd.read_csv('Attack.csv')
C:\Users\siddh\AppData\Local\Temp\ipykernel_19236\137588759.py:4: DtypeWarning: Columns (26,28,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df3=pd.read_csv('patientMonitoring.csv')
C:\Users\siddh\AppData\Local\Temp\ipykernel_19236\137588759.py:5: DtypeWarning: Columns (26,28,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat(
C:\Users\siddh\AppData\Local\Temp\ipykernel_19236\137588759.py:5: DtypeWarning: Columns (26,28,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat(


frame.time_delta  frame.time_relative  frame.len        ip.src  \
0          0.000000             0.000000         74  10.16.120.44   
1          0.000052             0.000052         74  10.16.120.72   
2          0.000008             0.000060         74  10.16.120.44   
3          0.000012             0.000072         74  10.16.120.72   
4          0.000003             0.000075         74  10.16.120.44   

         ip.dst  tcp.srcport  tcp.dstport   tcp.flags  tcp.time_delta  \
0  10.16.120.72        56808         1883  0x00000002        0.000000   
1  10.16.120.44         1883        56808  0x00000012        0.000052   
2  10.16.120.72        56810         1883  0x00000002        0.000000   
3  10.16.120.44         1883        56810  0x00000012        0.000012   
4  10.16.120.72        56812         1883  0x00000002        0.000000   

   tcp.len  ...  mqtt.qos  mqtt.retain  mqtt.topic  mqtt.topic_len  mqtt.ver  \
0        0  ...       0.0          0.0         0.0             0.0       0.0   
1        0  ...       0.0          0.0         0.0             0.0       0.0   
2        0  ...       0.0          0.0         0.0             0.0       0.0   
3        0  ...       0.0          0.0         0.0             0.0       0.0   
4        0  ...       0.0          0.0         0.0             0.0       0.0   

   mqtt.willmsg_len  ip.proto  ip.ttl   class  label  
0               0.0         6      64  Attack      1  
1               0.0         6      64  Attack      1  
2               0.0         6      64  Attack      1  
3               0.0         6      64  Attack      1  
4               0.0         6      64  Attack      1  

[5 rows x 52 columns]

In [3]:
df.drop('label',inplace=True,axis=1)

In [4]:
!pip install -U scikit-learn --user

In [5]:
from sklearn.preprocessing import LabelEncoder

lbl_enc_attack_type = LabelEncoder()
df['Attack_type_label'] = lbl_enc_attack_type.fit_transform(df['class'])
df

col_1 = df['Attack_type_label'].unique()
col_2 = list(lbl_enc_attack_type.inverse_transform(df['Attack_type_label'].unique()))

mapping_tree = pd.DataFrame({"Corresponding No.":col_1,"Attack Label":col_2})
mapping_tree

Corresponding No.           Attack Label
0                  0                 Attack
1                  1  environmentMonitoring
2                  2      patientMonitoring

In [6]:
list_cols = df.columns
ind_list_cols_labels = [3,4,7,22,25,26,28,35,37,40,44,50]    
sel_obj_cols = list_cols[ind_list_cols_labels]

In [7]:
for i in df[sel_obj_cols]:
    print(i,'\t',len(df[i].unique()), f'... & ... total length: {len(df)}')
    if len(df[i].unique())<1200:
        continue

ip.src 	 44 ... & ... total length: 188694
ip.dst 	 44 ... & ... total length: 188694
tcp.flags 	 8 ... & ... total length: 188694
tcp.payload 	 50526 ... & ... total length: 188694
tcp.checksum 	 45930 ... & ... total length: 188694
mqtt.clientid 	 1159 ... & ... total length: 188694
mqtt.conack.flags 	 3 ... & ... total length: 188694
mqtt.conflags 	 3 ... & ... total length: 188694
mqtt.hdrflags 	 14 ... & ... total length: 188694
mqtt.msg 	 24714 ... & ... total length: 188694
mqtt.topic 	 23440 ... & ... total length: 188694
class 	 3 ... & ... total length: 188694


In [8]:
ipsrc_lbl_enc = LabelEncoder()
ip_dst_lbl_enc = LabelEncoder()
tcp_flags_lbl_enc = LabelEncoder()
mqtt_conack_flag_lbl_enc = LabelEncoder()
mqtt_conflags_lbl_enc = LabelEncoder()
mqtt_hdrflags_lbl_enc = LabelEncoder()

In [9]:
df_fin = df.copy()
df_fin.drop(['tcp.payload','tcp.checksum','mqtt.clientid',
            'mqtt.msg','mqtt.topic','mqtt.conflag.willflag',
            'mqtt.conflag.retain','mqtt.conflag.reserved','tcp.flags.urg',
            'mqtt.conflag.qos','mqtt.conflag.passwd','mqtt.conack.val','ip.proto','mqtt.willmsg_len'],inplace=True,axis=1)

In [12]:
df_fin

frame.time_delta  frame.time_relative  frame.len        ip.src  \
0               0.000000             0.000000         74  10.16.120.44   
1               0.000052             0.000052         74  10.16.120.72   
2               0.000008             0.000060         74  10.16.120.44   
3               0.000012             0.000072         74  10.16.120.72   
4               0.000003             0.000075         74  10.16.120.44   
...                  ...                  ...        ...           ...   
188689          0.000196          6611.037621         78  10.5.126.165   
188690          0.000172          6611.037793         77  10.5.126.147   
188691          0.000126          6611.037919         77  10.5.126.147   
188692          0.000146          6611.038065         77  10.5.126.167   
188693          0.000147          6611.038212         77  10.5.126.167   

              ip.dst  tcp.srcport  tcp.dstport   tcp.flags  tcp.time_delta  \
0       10.16.120.72        56808         1883  0x00000002        0.000000   
1       10.16.120.44         1883        56808  0x00000012        0.000052   
2       10.16.120.72        56810         1883  0x00000002        0.000000   
3       10.16.120.44         1883        56810  0x00000012        0.000012   
4       10.16.120.72        56812         1883  0x00000002        0.000000   
...              ...          ...          ...         ...             ...   
188689   10.5.126.56        44993         1883  0x00000018        1.989358   
188690   10.5.126.56        38323         1883  0x00000018        1.989338   
188691   10.5.126.56        41889         1883  0x00000018        1.989337   
188692   10.5.126.56        35965         1883  0x00000018        1.989211   
188693   10.5.126.56        33251         1883  0x00000018        1.989194   

        tcp.len  ...  mqtt.kalive  mqtt.len  mqtt.msgtype  mqtt.qos  \
0             0  ...          0.0       0.0           0.0       0.0   
1             0  ...          0.0       0.0           0.0       0.0   
2             0  ...          0.0       0.0           0.0       0.0   
3             0  ...          0.0       0.0           0.0       0.0   
4             0  ...          0.0       0.0           0.0       0.0   
...         ...  ...          ...       ...           ...       ...   
188689       10  ...          0.0       8.0           3.0       0.0   
188690        9  ...          0.0       7.0           3.0       0.0   
188691        9  ...          0.0       7.0           3.0       0.0   
188692        9  ...          0.0       7.0           3.0       0.0   
188693        9  ...          0.0       7.0           3.0       0.0   

        mqtt.retain  mqtt.topic_len  mqtt.ver  ip.ttl              class  \
0               0.0             0.0       0.0      64             Attack   
1               0.0             0.0       0.0      64             Attack   
2               0.0             0.0       0.0      64             Attack   
3               0.0             0.0       0.0      64             Attack   
4               0.0             0.0       0.0      64             Attack   
...             ...             ...       ...     ...                ...   
188689          0.0             3.0       0.0      64  patientMonitoring   
188690          0.0             3.0       0.0      64  patientMonitoring   
188691          0.0             3.0       0.0      64  patientMonitoring   
188692          0.0             3.0       0.0      64  patientMonitoring   
188693          0.0             3.0       0.0      64  patientMonitoring   

        Attack_type_label  
0                       0  
1                       0  
2                       0  
3                       0  
4                       0  
...                   ...  
188689                  2  
188690                  2  
188691                  2  
188692                  2  
188693                  2  

[188694 rows x 38 columns]

In [10]:
list_corr_vals = df_fin.corr()
list_corr_vals['Attack_type_label']

ValueError: could not convert string to float: '10.16.120.44'

In [10]:
partial_list = list_corr_vals['Attack_type_label']
print(type(partial_list))
partial_list_index = partial_list.index
# print(partial_list_index)#,len(partial_list_index))
fin_sel_cols = []

print(len(list_corr_vals['Attack_type_label']))
#cnt=0
for i in range(len(list_corr_vals['Attack_type_label'])):    

    if list_corr_vals['Attack_type_label'][i] >= 0.40 or list_corr_vals['Attack_type_label'][i] <= -0.40:
        #cnt+=1
        tmp = list_corr_vals['Attack_type_label'][i]
        print(tmp,partial_list_index[i])
        fin_sel_cols.append(partial_list_index[i])
    

<class 'pandas.core.series.Series'>
31
0.7250371112787322 frame.time_relative
0.5565626225317978 tcp.flags.push
0.7622946163363997 tcp.hdr_len
-0.4182872083202054 ip.ttl
1.0 Attack_type_label


In [11]:
fin_sel_cols

['frame.time_relative',
 'tcp.flags.push',
 'tcp.hdr_len',
 'ip.ttl',
 'Attack_type_label']

In [12]:
final_ds = df_fin[fin_sel_cols]
final_ds

X = final_ds.drop('Attack_type_label', axis = 1)
X=X.reset_index(drop=True)
X

frame.time_relative  tcp.flags.push  tcp.hdr_len  ip.ttl
0                  0.000000               0           40      64
1                  0.000052               0           40      64
2                  0.000060               0           40      64
3                  0.000072               0           40      64
4                  0.000075               0           40      64
...                     ...             ...          ...     ...
188689          6611.037621               1           32      64
188690          6611.037793               1           32      64
188691          6611.037919               1           32      64
188692          6611.038065               1           32      64
188693          6611.038212               1           32      64

[188694 rows x 4 columns]

In [13]:
y = final_ds['Attack_type_label']
y

0         0
1         0
2         0
3         0
4         0
         ..
188689    2
188690    2
188691    2
188692    2
188693    2
Name: Attack_type_label, Length: 188694, dtype: int32

In [14]:
import torch
from torchvision import datasets, transforms
import numpy as np
from opacus import PrivacyEngine
from tqdm import tqdm
import pandas as pd
import numpy as np
import seaborn as sns
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader
from torch.utils.data import TensorDataset
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler

C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: '[WinError 127] The specified procedure could not be found'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(


In [15]:
class HeartDiseaseModel(nn.Module):
    def __init__(self, input_size):
        super(HeartDiseaseModel, self).__init__()
        self.fc1 = nn.Linear(input_size, 256)
        self.relu1 = nn.ReLU()
        self.fc2 = nn.Linear(256,128)
        self.relu2 = nn.ReLU()
        self.fc3 = nn.Linear(128, 64)
        self.relu3 = nn.ReLU()
#         self.dropout = nn.Dropout(0.5)
        self.fc4 = nn.Linear(64, 32)
        self.relu4 = nn.ReLU()
        
        self.fc5 = nn.Linear(32, 3)
        self.Softmax = nn.Softmax(dim=1)

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu1(x)
        x = self.fc2(x)
        x = self.relu2(x)
        x = self.fc3(x)
        x = self.relu3(x)
#         x = self.dropout(x)
        x = self.fc4(x)
        x = self.relu4(x)
        x = self.fc5(x)
        x = self.Softmax(x)
        return x

input_size = 4  # number of features

In [16]:
model = HeartDiseaseModel(input_size)
y = y.to_numpy()
X = X.to_numpy()
# scaler = StandardScaler()
# X = scaler.fit_transform(X)
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=5)

# def df_to_tensor(df, target_col=None):
#     if target_col:
#         target = torch.from_numpy(df[target_col].values).long()
#         data = df.drop(target_col, axis=1)
#     else:
#         target = None
#         data = df
#     return torch.from_numpy(data.values).float(), target

# # X_traint = df_to_tensor(X_train)
# # y_traint = df_to_tensor(y_train)
# # X_testt = df_to_tensor(X_test)
# # y_testt = df_to_tensor(y_test)
# X_train, y_train = df_to_tensor(train_ds, target_col='Attack_type_label')
# X_test, y_test = df_to_tensor(test_ds, target_col='Attack_type_label')

# train_ds = TensorDataset(X_traint, y_traint)
# test_ds = TensorDataset(X_testt, y_testt)

# # create data loaders
# batch_size = 5000

# train_dataloader = DataLoader(train_ds, batch_size=batch_size, shuffle=True)
# test_dataloader = DataLoader(test_ds, batch_size=batch_size, shuffle=True)

def df_to_tensor(df):
    return torch.from_numpy(df).float()

X = df_to_tensor(X)
y = df_to_tensor(y).long()

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create data loaders
batch_size = 2000 # Set the desired batch size
train_ds = TensorDataset(X_train, y_train)
test_ds = TensorDataset(X_test, y_test)
train_dataloader = DataLoader(train_ds, batch_size=batch_size, shuffle=True)
test_dataloader = DataLoader(test_ds, batch_size=batch_size, shuffle=False)
delta=1e-7
epochs =20
privacy_engine = PrivacyEngine()
loss_fn = nn.CrossEntropyLoss() # Binary Cross Entropy
optimizer = torch.optim.Adam(model.parameters(), lr=1e-6)
model, optimizer, dataloader = privacy_engine.make_private_with_epsilon(module=model,optimizer=optimizer,data_loader=train_dataloader,
                                                         max_grad_norm=1.0,target_epsilon=7, epochs=epochs, target_delta= 1e-5)
criterion = nn.CrossEntropyLoss()
epsilon_values = []

C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\opacus\privacy_engine.py:142: UserWarning: Secure RNG turned off. This is perfectly fine for experimentation as it allows for much faster training performance, but remember to turn it on and retrain one last time before production with ``secure_mode`` turned on.
  warnings.warn(
C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\opacus\accountants\analysis\rdp.py:332: UserWarning: Optimal order is the largest alpha. Please consider expanding the range of alphas to get a tighter privacy bound.
  warnings.warn(
C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\opacus\accountants\analysis\prv\prvs.py:50: RuntimeWarning: invalid value encountered in log
  z = np.log((np.exp(t) + q - 1) / q)


In [17]:
epsilon_values = []
def train(model, train_dataloader, optimizer, epoch):
    model.train()
    losses = []
    for batch, (data, target) in enumerate(train_dataloader):
        optimizer.zero_grad()
        output = model(data)
        loss = criterion(output, target)  # Use CrossEntropyLoss for multi-class classification
        loss.backward()
        optimizer.step()
        losses.append(loss.item())
    epsilon = float(privacy_engine.get_epsilon(delta))
    epsilon_values.append(epsilon)
    print('Epoch: {}, Avg. Loss: {:.4f}'.format(epoch, np.mean(losses)))
    return epsilon_values

def test(model, test_dataloader):
    model.eval()
    predictions = []
    targets = []
    with torch.no_grad():
        for data, target in test_dataloader:
            output = model(data)
            predicted_labels = torch.argmax(output, dim=1)
            predictions.extend(predicted_labels.tolist())
            targets.extend(target.tolist())
    acc = accuracy_score(targets, predictions)
    print('Test Accuracy: {:.4f}'.format(acc))
    print('Confusion Matrix:')
    print(confusion_matrix(targets, predictions))
    print('Classification Report:')
    print(classification_report(targets, predictions))
    return acc

In [18]:
accuracies = []
epsilon_list=[]
epsilon_list_total=[]
for epoch in range(1, epochs):
    epsilon_list=train(model, train_dataloader, optimizer, epoch)
    print('epsilon list is ', epsilon_list)
#     test(model, test_dataloader)
    acc = test(model, test_dataloader)
    accuracies.append(acc)
    print('Accuracy list is ',accuracies)

C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\torch\nn\modules\module.py:1117: UserWarning: Using a non-full backward hook when the forward contains multiple autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_input. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using a non-full backward hook when the forward contains multiple autograd Nodes "


Epoch: 1, Avg. Loss: 1.1668
epsilon list is  [3.96945306156586]
Test Accuracy: 0.5563
Confusion Matrix:
[[15261   677    89]
 [  519  5673    64]
 [  642 14755    59]]
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.95      0.94     16027
           1       0.27      0.91      0.41      6256
           2       0.28      0.00      0.01     15456

    accuracy                           0.56     37739
   macro avg       0.49      0.62      0.45     37739
weighted avg       0.55      0.56      0.47     37739

Accuracy list is  [0.5562680516176899]


C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\torch\nn\modules\module.py:1117: UserWarning: Using a non-full backward hook when the forward contains multiple autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_input. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using a non-full backward hook when the forward contains multiple autograd Nodes "
C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\opacus\accountants\analysis\prv\prvs.py:50: RuntimeWarning: invalid value encountered in log
  z = np.log((np.exp(t) + q - 1) / q)


Epoch: 2, Avg. Loss: 1.1537
epsilon list is  [3.96945306156586, 4.485278647937415]
Test Accuracy: 0.5570
Confusion Matrix:
[[15437   590     0]
 [  672  5584     0]
 [  783 14673     0]]
Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.96      0.94     16027
           1       0.27      0.89      0.41      6256
           2       0.00      0.00      0.00     15456

    accuracy                           0.56     37739
   macro avg       0.39      0.62      0.45     37739
weighted avg       0.43      0.56      0.47     37739

Accuracy list is  [0.5562680516176899, 0.5570099896658629]


C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\

Epoch: 3, Avg. Loss: 1.1401
epsilon list is  [3.96945306156586, 4.485278647937415, 4.896522927121258]
Test Accuracy: 0.5587
Confusion Matrix:
[[15610   417     0]
 [  781  5475     0]
 [  922 14534     0]]
Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.97      0.94     16027
           1       0.27      0.88      0.41      6256
           2       0.00      0.00      0.00     15456

    accuracy                           0.56     37739
   macro avg       0.39      0.62      0.45     37739
weighted avg       0.43      0.56      0.47     37739

Accuracy list is  [0.5562680516176899, 0.5570099896658629, 0.5587058480616869]


C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\

Epoch: 4, Avg. Loss: 1.1254
epsilon list is  [3.96945306156586, 4.485278647937415, 4.896522927121258, 5.2549394301994585]
Test Accuracy: 0.5572
Confusion Matrix:
[[15706   320     1]
 [  932  5324     0]
 [ 1058 14398     0]]
Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.98      0.93     16027
           1       0.27      0.85      0.40      6256
           2       0.00      0.00      0.00     15456

    accuracy                           0.56     37739
   macro avg       0.38      0.61      0.45     37739
weighted avg       0.42      0.56      0.46     37739

Accuracy list is  [0.5562680516176899, 0.5570099896658629, 0.5587058480616869, 0.5572484697527756]


C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\torch\nn\modules\module.py:1117: UserWarning: Using a non-full backward hook when the forward contains multiple autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_input. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using a non-full backward hook when the forward contains multiple autograd Nodes "
C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\opacus\accountants\analysis\prv\prvs.py:50: RuntimeWarning: invalid value encountered in log
  z = np.log((np.exp(t) + q - 1) / q)


Epoch: 5, Avg. Loss: 1.0547
epsilon list is  [3.96945306156586, 4.485278647937415, 4.896522927121258, 5.2549394301994585, 5.5795968759373915]
Test Accuracy: 0.7957
Confusion Matrix:
[[15785     0   242]
 [ 1079     0  5177]
 [ 1212     0 14244]]
Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.98      0.93     16027
           1       0.00      0.00      0.00      6256
           2       0.72      0.92      0.81     15456

    accuracy                           0.80     37739
   macro avg       0.53      0.64      0.58     37739
weighted avg       0.67      0.80      0.73     37739

Accuracy list is  [0.5562680516176899, 0.5570099896658629, 0.5587058480616869, 0.5572484697527756, 0.7957020588780837]


C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\

Epoch: 6, Avg. Loss: 0.8705
epsilon list is  [3.96945306156586, 4.485278647937415, 4.896522927121258, 5.2549394301994585, 5.5795968759373915, 5.880160066240218]
Test Accuracy: 0.7959
Confusion Matrix:
[[15714     0   313]
 [ 1002     0  5254]
 [ 1134     0 14322]]
Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.98      0.93     16027
           1       0.00      0.00      0.00      6256
           2       0.72      0.93      0.81     15456

    accuracy                           0.80     37739
   macro avg       0.53      0.64      0.58     37739
weighted avg       0.67      0.80      0.73     37739

Accuracy list is  [0.5562680516176899, 0.5570099896658629, 0.5587058480616869, 0.5572484697527756, 0.7957020588780837, 0.7958875433901269]


C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\

Epoch: 7, Avg. Loss: 0.8537
epsilon list is  [3.96945306156586, 4.485278647937415, 4.896522927121258, 5.2549394301994585, 5.5795968759373915, 5.880160066240218, 6.162341076783797]
Test Accuracy: 0.7975
Confusion Matrix:
[[15685     0   342]
 [  921     0  5335]
 [ 1046     0 14410]]
Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.98      0.93     16027
           1       0.00      0.00      0.00      6256
           2       0.72      0.93      0.81     15456

    accuracy                           0.80     37739
   macro avg       0.54      0.64      0.58     37739
weighted avg       0.67      0.80      0.73     37739

Accuracy list is  [0.5562680516176899, 0.5570099896658629, 0.5587058480616869, 0.5572484697527756, 0.7957020588780837, 0.7958875433901269, 0.7974509128487771]


C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\

Epoch: 8, Avg. Loss: 0.8443
epsilon list is  [3.96945306156586, 4.485278647937415, 4.896522927121258, 5.2549394301994585, 5.5795968759373915, 5.880160066240218, 6.162341076783797, 6.429850142124402]
Test Accuracy: 0.7978
Confusion Matrix:
[[15676     0   351]
 [  898     0  5358]
 [ 1025     0 14431]]
Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.98      0.93     16027
           1       0.00      0.00      0.00      6256
           2       0.72      0.93      0.81     15456

    accuracy                           0.80     37739
   macro avg       0.54      0.64      0.58     37739
weighted avg       0.67      0.80      0.73     37739

Accuracy list is  [0.5562680516176899, 0.5570099896658629, 0.5587058480616869, 0.5572484697527756, 0.7957020588780837, 0.7958875433901269, 0.7974509128487771, 0.7977688862979941]


C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\

Epoch: 9, Avg. Loss: 0.8356
epsilon list is  [3.96945306156586, 4.485278647937415, 4.896522927121258, 5.2549394301994585, 5.5795968759373915, 5.880160066240218, 6.162341076783797, 6.429850142124402, 6.685264946930678]
Test Accuracy: 0.7978
Confusion Matrix:
[[15676     0   351]
 [  898     0  5358]
 [ 1025     0 14431]]
Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.98      0.93     16027
           1       0.00      0.00      0.00      6256
           2       0.72      0.93      0.81     15456

    accuracy                           0.80     37739
   macro avg       0.54      0.64      0.58     37739
weighted avg       0.67      0.80      0.73     37739

Accuracy list is  [0.5562680516176899, 0.5570099896658629, 0.5587058480616869, 0.5572484697527756, 0.7957020588780837, 0.7958875433901269, 0.7974509128487771, 0.7977688862979941, 0.7977688862979941]


C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\

Epoch: 10, Avg. Loss: 0.8277
epsilon list is  [3.96945306156586, 4.485278647937415, 4.896522927121258, 5.2549394301994585, 5.5795968759373915, 5.880160066240218, 6.162341076783797, 6.429850142124402, 6.685264946930678, 6.93046275789818]
Test Accuracy: 0.7975
Confusion Matrix:
[[15676     0   351]
 [  910     0  5346]
 [ 1037     0 14419]]
Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.98      0.93     16027
           1       0.00      0.00      0.00      6256
           2       0.72      0.93      0.81     15456

    accuracy                           0.80     37739
   macro avg       0.54      0.64      0.58     37739
weighted avg       0.67      0.80      0.73     37739

Accuracy list is  [0.5562680516176899, 0.5570099896658629, 0.5587058480616869, 0.5572484697527756, 0.7957020588780837, 0.7958875433901269, 0.7974509128487771, 0.7977688862979941, 0.7977688862979941, 0.7974509128487771]


C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\

Epoch: 11, Avg. Loss: 0.8202
epsilon list is  [3.96945306156586, 4.485278647937415, 4.896522927121258, 5.2549394301994585, 5.5795968759373915, 5.880160066240218, 6.162341076783797, 6.429850142124402, 6.685264946930678, 6.93046275789818, 7.16686361199382]
Test Accuracy: 0.7980
Confusion Matrix:
[[15708     0   319]
 [  923     0  5333]
 [ 1050     0 14406]]
Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.98      0.93     16027
           1       0.00      0.00      0.00      6256
           2       0.72      0.93      0.81     15456

    accuracy                           0.80     37739
   macro avg       0.54      0.64      0.58     37739
weighted avg       0.67      0.80      0.73     37739

Accuracy list is  [0.5562680516176899, 0.5570099896658629, 0.5587058480616869, 0.5572484697527756, 0.7957020588780837, 0.7958875433901269, 0.7974509128487771, 0.7977688862979941, 0.7977688862979941, 0.7974509128487771, 0.7979543708100374

C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\

Epoch: 12, Avg. Loss: 0.8135
epsilon list is  [3.96945306156586, 4.485278647937415, 4.896522927121258, 5.2549394301994585, 5.5795968759373915, 5.880160066240218, 6.162341076783797, 6.429850142124402, 6.685264946930678, 6.93046275789818, 7.16686361199382, 7.395575584657975]
Test Accuracy: 0.7964
Confusion Matrix:
[[15708     0   319]
 [  964     0  5292]
 [ 1109     0 14347]]
Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.98      0.93     16027
           1       0.00      0.00      0.00      6256
           2       0.72      0.93      0.81     15456

    accuracy                           0.80     37739
   macro avg       0.53      0.64      0.58     37739
weighted avg       0.67      0.80      0.73     37739

Accuracy list is  [0.5562680516176899, 0.5570099896658629, 0.5587058480616869, 0.5572484697527756, 0.7957020588780837, 0.7958875433901269, 0.7974509128487771, 0.7977688862979941, 0.7977688862979941, 0.7974509128487771,

C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\

Epoch: 13, Avg. Loss: 0.8074
epsilon list is  [3.96945306156586, 4.485278647937415, 4.896522927121258, 5.2549394301994585, 5.5795968759373915, 5.880160066240218, 6.162341076783797, 6.429850142124402, 6.685264946930678, 6.93046275789818, 7.16686361199382, 7.395575584657975, 7.617484178401589]
Test Accuracy: 0.7961
Confusion Matrix:
[[15714     0   313]
 [  997     0  5259]
 [ 1127     0 14329]]
Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.98      0.93     16027
           1       0.00      0.00      0.00      6256
           2       0.72      0.93      0.81     15456

    accuracy                           0.80     37739
   macro avg       0.53      0.64      0.58     37739
weighted avg       0.67      0.80      0.73     37739

Accuracy list is  [0.5562680516176899, 0.5570099896658629, 0.5587058480616869, 0.5572484697527756, 0.7957020588780837, 0.7958875433901269, 0.7974509128487771, 0.7977688862979941, 0.7977688862979941, 

C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\

Epoch: 14, Avg. Loss: 0.8019
epsilon list is  [3.96945306156586, 4.485278647937415, 4.896522927121258, 5.2549394301994585, 5.5795968759373915, 5.880160066240218, 6.162341076783797, 6.429850142124402, 6.685264946930678, 6.93046275789818, 7.16686361199382, 7.395575584657975, 7.617484178401589, 7.833309834704802]
Test Accuracy: 0.7963
Confusion Matrix:
[[15746     0   281]
 [ 1019     0  5237]
 [ 1152     0 14304]]
Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.98      0.93     16027
           1       0.00      0.00      0.00      6256
           2       0.72      0.93      0.81     15456

    accuracy                           0.80     37739
   macro avg       0.53      0.64      0.58     37739
weighted avg       0.67      0.80      0.73     37739

Accuracy list is  [0.5562680516176899, 0.5570099896658629, 0.5587058480616869, 0.5572484697527756, 0.7957020588780837, 0.7958875433901269, 0.7974509128487771, 0.7977688862979941, 0

C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\

Epoch: 15, Avg. Loss: 0.7967
epsilon list is  [3.96945306156586, 4.485278647937415, 4.896522927121258, 5.2549394301994585, 5.5795968759373915, 5.880160066240218, 6.162341076783797, 6.429850142124402, 6.685264946930678, 6.93046275789818, 7.16686361199382, 7.395575584657975, 7.617484178401589, 7.833309834704802, 8.043648604614836]
Test Accuracy: 0.7955
Confusion Matrix:
[[15748     0   279]
 [ 1044     0  5212]
 [ 1181     0 14275]]
Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.98      0.93     16027
           1       0.00      0.00      0.00      6256
           2       0.72      0.92      0.81     15456

    accuracy                           0.80     37739
   macro avg       0.53      0.64      0.58     37739
weighted avg       0.67      0.80      0.73     37739

Accuracy list is  [0.5562680516176899, 0.5570099896658629, 0.5587058480616869, 0.5572484697527756, 0.7957020588780837, 0.7958875433901269, 0.7974509128487771, 0.

C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\

Epoch: 16, Avg. Loss: 0.7920
epsilon list is  [3.96945306156586, 4.485278647937415, 4.896522927121258, 5.2549394301994585, 5.5795968759373915, 5.880160066240218, 6.162341076783797, 6.429850142124402, 6.685264946930678, 6.93046275789818, 7.16686361199382, 7.395575584657975, 7.617484178401589, 7.833309834704802, 8.043648604614836, 8.249004309407873]
Test Accuracy: 0.7962
Confusion Matrix:
[[15798     0   229]
 [ 1073     0  5183]
 [ 1205     0 14251]]
Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.99      0.93     16027
           1       0.00      0.00      0.00      6256
           2       0.72      0.92      0.81     15456

    accuracy                           0.80     37739
   macro avg       0.53      0.64      0.58     37739
weighted avg       0.67      0.80      0.73     37739

Accuracy list is  [0.5562680516176899, 0.5570099896658629, 0.5587058480616869, 0.5572484697527756, 0.7957020588780837, 0.7958875433901269, 0.7

C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\

Epoch: 17, Avg. Loss: 0.7879
epsilon list is  [3.96945306156586, 4.485278647937415, 4.896522927121258, 5.2549394301994585, 5.5795968759373915, 5.880160066240218, 6.162341076783797, 6.429850142124402, 6.685264946930678, 6.93046275789818, 7.16686361199382, 7.395575584657975, 7.617484178401589, 7.833309834704802, 8.043648604614836, 8.249004309407873, 8.449802628304433]
Test Accuracy: 0.7959
Confusion Matrix:
[[15810     0   217]
 [ 1115     0  5141]
 [ 1230     0 14226]]
Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.99      0.93     16027
           1       0.00      0.00      0.00      6256
           2       0.73      0.92      0.81     15456

    accuracy                           0.80     37739
   macro avg       0.53      0.64      0.58     37739
weighted avg       0.67      0.80      0.73     37739

Accuracy list is  [0.5562680516176899, 0.5570099896658629, 0.5587058480616869, 0.5572484697527756, 0.7957020588780837, 0.79

C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\

Epoch: 18, Avg. Loss: 0.7840
epsilon list is  [3.96945306156586, 4.485278647937415, 4.896522927121258, 5.2549394301994585, 5.5795968759373915, 5.880160066240218, 6.162341076783797, 6.429850142124402, 6.685264946930678, 6.93046275789818, 7.16686361199382, 7.395575584657975, 7.617484178401589, 7.833309834704802, 8.043648604614836, 8.249004309407873, 8.449802628304433, 8.646412209010967]
Test Accuracy: 0.7954
Confusion Matrix:
[[15835     0   192]
 [ 1139     0  5117]
 [ 1273     0 14183]]
Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.99      0.92     16027
           1       0.00      0.00      0.00      6256
           2       0.73      0.92      0.81     15456

    accuracy                           0.80     37739
   macro avg       0.53      0.64      0.58     37739
weighted avg       0.67      0.80      0.72     37739

Accuracy list is  [0.5562680516176899, 0.5570099896658629, 0.5587058480616869, 0.5572484697527756, 0.795

C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\

Epoch: 19, Avg. Loss: 0.7808
epsilon list is  [3.96945306156586, 4.485278647937415, 4.896522927121258, 5.2549394301994585, 5.5795968759373915, 5.880160066240218, 6.162341076783797, 6.429850142124402, 6.685264946930678, 6.93046275789818, 7.16686361199382, 7.395575584657975, 7.617484178401589, 7.833309834704802, 8.043648604614836, 8.249004309407873, 8.449802628304433, 8.646412209010967, 8.83915246432873]
Test Accuracy: 0.7951
Confusion Matrix:
[[15836     0   191]
 [ 1162     0  5094]
 [ 1287     0 14169]]
Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.99      0.92     16027
           1       0.00      0.00      0.00      6256
           2       0.73      0.92      0.81     15456

    accuracy                           0.80     37739
   macro avg       0.53      0.63      0.58     37739
weighted avg       0.67      0.80      0.72     37739

Accuracy list is  [0.5562680516176899, 0.5570099896658629, 0.5587058480616869, 0.55724

C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\siddh\anaconda3\envs\gpu2\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
